In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import joblib

In [25]:
df = pd.read_csv('../House_Rent_Dataset_TN_synthetic_text_1500_preprocessed.csv')
df.head()

,Rent,Posted On,BHK,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,...,Listing_Description,Amenities_Text,Landmarks_Text,Reviews_Text,Complaints_Text,Lease_Rules_Text,Inquiry_Text,Inspection_Notes_Text,Scam_Flag,Scam_Rationale
0,15000,2022-07-06,2,1100,1 out of 2,super area,medavakkam,chennai,semi-furnished,bachelors,...,2 bhk semi-furnished home of 1100 sq ft (super...,"rainwater harvesting, play area, solar lightin...",near college (3.3 km); near hospital (0.6 km);...,clean and well maintained building. | safe are...,not_applicable,no smoking inside the house. tenant must follo...,looking for a 2 bhk near medavakkam within inr...,flooring shows normal wear. bathrooms are clea...,no,not_applicable
1,6500,2022-05-21,2,1000,ground out of 1,super area,"urapakkam, vandalur r.f, gst road",chennai,semi-furnished,bachelors/family,...,2 bhk semi-furnished home of 1000 sq ft (super...,"visitor parking, cctv, power backup, club hous...",near market (3.5 km); near school (0.8 km); ne...,clean and well maintained building. | good wat...,listing photos did not match actual house.,security deposit is two months rent. no loud m...,"want to move in next month, budget around inr ...",flooring shows normal wear. good natural light...,yes,owner refused physical visit. | asked for paym...
2,90000,2022-05-20,3,2400,1 out of 3,carpet area,"r.a puram, mandaiveli",chennai,semi-furnished,bachelors/family,...,3 bhk semi-furnished home of 2400 sq ft (carpe...,"waste management, power backup, lift, fire saf...",near pharmacy (0.6 km); near church (0.6 km),good water supply and quiet neighborhood. | ma...,not_applicable,security deposit is two months rent. maintenan...,"want to move in next month, budget around inr ...",electrical fittings are working properly. floo...,no,not_applicable
3,200000,2022-07-10,3,3000,1 out of 1,super area,madras boat club road,chennai,furnished,family,...,3 bhk furnished home of 3000 sq ft (super area...,"security, play area, gym, maintenance staff, w...",near mosque (3.4 km); near atm (1.8 km),parking is convenient and secure. | spacious r...,not_applicable,maintenance charges are extra. pets allowed on...,"want to move in next month, budget around inr ...",walls need minor repainting. good natural ligh...,no,not_applicable
4,15000,2022-06-25,1,650,ground out of 2,carpet area,kambar colony,chennai,semi-furnished,bachelors/family,...,1 bhk semi-furnished home of 650 sq ft (carpet...,"maintenance staff, security, rainwater harvest...",near atm (3.5 km); near hospital (3.8 km); nea...,easy access to public transport. | maintenance...,not_applicable,pets allowed only with prior approval. no loud...,"need a semi-furnished home in chennai, prefer ...",bathrooms are clean and functional. walls need...,no,not_applicable

In [26]:
df['Rent_Category'] = pd.qcut(df['Rent'], q=4, labels=['Budget', 'Standard', 'Premium', 'Luxury'])
df[['Rent', 'Rent_Category']].head()

     Rent Rent_Category
0   15000       Premium
1    6500        Budget
2   90000        Luxury
3  200000        Luxury
4   15000       Premium

In [27]:
X = df[['BHK', 'Size', 'Bathroom', 'Area Type', 'Furnishing Status', 'Tenant Preferred', 'Point of Contact']]
y = df['Rent_Category']

X = pd.get_dummies(X)
X.head()

,BHK,Size,Bathroom,Area Type_built area,Area Type_carpet area,Area Type_super area,Furnishing Status_furnished,Furnishing Status_semi-furnished,Furnishing Status_unfurnished,Tenant Preferred_bachelors,Tenant Preferred_bachelors/family,Tenant Preferred_family,Point of Contact_contact agent,Point of Contact_contact owner
0,2,1100,2,False,False,True,False,True,False,True,False,False,False,True
1,2,1000,2,False,False,True,False,True,False,False,True,False,False,True
2,3,2400,3,False,True,False,False,True,False,False,True,False,True,False
3,3,3000,4,False,False,True,True,False,False,False,False,True,True,False
4,1,650,1,False,True,False,False,True,False,False,True,False,False,True

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

model.score(X_test, y_test)

c:\Users\dell_\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.55

In [29]:
y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[47  1 13 11]
 [ 2 60 14  1]
 [11 23 35 21]
 [21  5 12 23]]
              precision    recall  f1-score   support

      Budget       0.58      0.65      0.61        72
      Luxury       0.67      0.78      0.72        77
     Premium       0.47      0.39      0.43        90
    Standard       0.41      0.38      0.39        61

    accuracy                           0.55       300
   macro avg       0.53      0.55      0.54       300
weighted avg       0.54      0.55      0.54       300

In [30]:
joblib.dump(model, 'house_rent_multiclass_logistic_rent_tier.pkl')

['house_rent_multiclass_logistic_rent_tier.pkl']

In [31]:
md = joblib.load("house_rent_multiclass_logistic_rent_tier.pkl")